
pipeline:
  prebuild:
    image: docker
    volumes:
      - /var/run/docker.sock : /var/run/docker.sock
    commands: 
      - docker --version
  test:
    image: node:${NODE_VERSION}
    commands:
      - echo Running in $NODE_ENV mode
      - npm -v
      - node -v
      - npm run test
    environment:
      - NODE_ENV: staging
  build:
    image: node:latest
    commands: 
      - npm run build
      - npm run server
matrix:
  NODE_VERSION:
    - latest
branches: master