
pipeline:
  prebuild:
    image: docker
    volumes:
      - /var/run/docker.sock : /var/run/docker.sock
    commands: 
      - docker --version
  test:
    image: node:${NODE_VERSION}
    commands:
      - echo Running $NODE_ENV mode
      - npm -v
      - node -v
      - npm run test
    environment:
      - NODE_ENV: staging
matrix:
  NODE_VERSION:
    - latest
    - 9
    - 8
branches: master